module.exports = {
	semi: false,
	singleQuote: true,
	jsxSingleQuote: false,
	printWidth: 180,
	htmlWhitespaceSensitivity: "strict",
	tabWidth: 2,
	useTabs: false,
	singleAttributePerLine: false,
	trailingComma: "es5",
	endOfLine: "lf",
	bracketSpacing: false,
	bracketSameLine: true,
	jsxBracketSameLine: true,
};
